### ISSUE TITLE
Add a test case that uses the bellperson adapter to generate R1CS

### ISSUE THREAD

**Issue by srinathsetty** [microsoft/Nova#10]

**Comment by arthurgreef** [comment]
Hi Srinath - are you still working on this? It would be really nice to have. Thanks.

**Comment by srinathsetty** [comment]
@arthurgreef Yes, we have some test cases in the verifier_circuit branch and we will port them over to the main branch.

@rozbb Good point! Yes, adding such an interface will be quite straightforward given the bellperson adapter already in the codebase. We will add such an interface once we have recursion in place.

**Comment by srinathsetty** [comment]
We now have some tests in the `tests` folder. I'll close this issue for now. An API like `create_random_proof` is coming soon.
