### ISSUE TITLE
Do you have plan for SuperNova?

### ISSUE THREAD

**Issue by ChengYueJia** [microsoft/Nova#120]
I've heard you have a newest protocol named SuperNova. https://eprint.iacr.org/2021/370.pdf
* Do you have a plan to impl? when?

**Comment by srinathsetty** [comment]
We will implement it in the near future. Thanks for your interest!

**Comment by matthiasgoergens** [comment]
Has the near future arrived, yet?

**Comment by wyattbenno777** [comment]
I started this in a fork. I plan on using the NIFS code that already exists.
It seems like most of the work will be around the selector, mux, and WRITE functions.

R1CS is first but I am following closely on the PSE CCS implementation.

https://github.com/wyattbenno777/SuperNova/tree/supernova

Let me know if someone is already doing this! 🙏
