### ISSUE TITLE
Is Nova quantum ready?

### ISSUE THREAD

**Issue by Anderssorby** [microsoft/Nova#164]
Quatum computing is seeing exponential development and it is conceivable that we will be able to run Shor's algorithm within 2030. That would break all convetional public key algorithms based on the hardness of prime factoring. It would also render all zk-SNARK-proofs compromised for forgery. Therefore switching to quantum secure cryptography is a must for serious application now even if the crack is some years away. Old proofs will be rendered entirely compromised and useless after that point. Therefore you would either need a system to upgrade and detrust old proofs, which would require recomputing all of them, or just start off quantum secure. The latter is definitely more realistic.

https://www.ncsc.gov.uk/whitepaper/preparing-for-quantum-safe-cryptography

**Comment by srinathsetty** [comment]
Nova relies on additively homomorphic commitments to vectors. In the current implementation, this is based on elliptic curves, so Nova is not quantum-safe. In the future, if one builds an efficient commitment scheme based on quantum-safe primitives, Nova can use them.
