### ISSUE TITLE
Guidance on Using Poseidon Hash in Custom Circuits

### ISSUE THREAD

**Issue by suniljalandhra** [microsoft/Nova#176]
I'm trying to incorporate Poseidon hash functionality into my own custom circuits. However, I'm facing some challenges and could use some guidance on how to properly integrate and utilize the Poseidon hash circuit.

**Steps to Reproduce:**
Attempt to incorporate Poseidon hash into a custom circuit.
Encounter difficulties in understanding the integration process and utilizing the hash algorithm effectively.
Struggle to find relevant documentation or examples within the Nova repository that specifically address the usage of Poseidon hash in custom circuits.

**Expected Behavior:**
I would appreciate some guidance or documentation on how to effectively incorporate and utilize the Poseidon hash algorithm in custom circuits within the Nova repository. This would enable me to leverage the benefits of Poseidon hash within my own custom circuit designs.

**Comment by srinathsetty** [comment]
Hi @suniljalandhra, thanks for your interest in Nova! 

I'm not entirely sure I understand the issue. Are you looking to use Poseidon from within a step circuit?

**Comment by suniljalandhra** [comment]
Yes, I want to use it inside a step circuit.

**Comment by srinathsetty** [comment]
Hi @suniljalandhra: For use inside a step circuit, a natural approach is to use the neptune crate: https://docs.rs/neptune/10.0.0/neptune/.

In particular, please see the code here: https://github.com/microsoft/Nova/blob/main/src/provider/poseidon.rs#L158. Similar code can be written directly inside a step circuit to invoke Poseidon implementation provided by neptune.
