### ISSUE TITLE
In nifs.rs's  test_tiny_r1cs() case,  why the  num_vars = 4?

### ISSUE THREAD

**Issue by readygo67** [microsoft/Nova#186]
I think there only are Z0, Z1, Z3 3 variables, so the num_vars should be 3.

```
fn test_tiny_r1cs() {
    let one = S::one();
    let (num_cons, num_vars, num_io, A, B, C) = {
      let num_cons = 4;  
      let num_vars = 4;
      let num_io = 2;

      // Consider a cubic equation: `x^3 + x + 5 = y`, where `x` and `y` are respectively the input and output.
      // The R1CS for this problem consists of the following constraints:
      // `I0 * I0 - Z0 = 0`
      // `Z0 * I0 - Z1 = 0`
      // `(Z1 + I0) * 1 - Z2 = 0`
      // `(Z2 + 5) * 1 - I1 = 0`
     .... 
```

**Comment by srinathsetty** [comment]
Good catch! It was set to 4 (to be a power of 2, but it is unnecessary). The witness was also padded with a zero as a result. I've fixed it in a PR: https://github.com/microsoft/Nova/pull/187

**Comment by readygo67** [comment]
Thanks for clarification.
In this stage,  assign (number of actual use variables)  = num_vars  is clear and make sense, though they will be padded to be power of 2 later.
