### ISSUE TITLE
Typo in paper "Revisiting the Nova Proof System on a Cycle of Curves"

### ISSUE THREAD

**Issue by 3for** [microsoft/Nova#190]
The [Revisiting the Nova Proof System on a Cycle of Curves](https://eprint.iacr.org/2023/969.pdf) paper is great.
Page 5:
![image](https://github.com/microsoft/Nova/assets/30716372/8509eaa4-1ede-4a77-8815-4ab757d1feff)

Page 12:
![image](https://github.com/microsoft/Nova/assets/30716372/9085475f-2070-4121-9ed3-4d4c6c4583ad)

**Comment by srinathsetty** [comment]
Thanks, for reporting! We'll fix these!
