### ISSUE TITLE
Why the type of "x" is vector?

### ISSUE THREAD

**Issue by intstringnum** [microsoft/Nova#193]
Hi, I've been interested in the paper, and I've been looking at the implementation.
i have a question about type of instance.

in my knowledge, i think the type of x should be G::Scalar not Vector!
is this have any reason using Vec?
I want to know if I miss anything
Thank you

pub struct RelaxedR1CSInstance<G: Group> {
  pub(crate) comm_W: Commitment<G>,
  pub(crate) comm_E: Commitment<G>,
  pub(crate) X: Vec<G::Scalar>,
  pub(crate) u: G::Scalar,
}

**Comment by srinathsetty** [comment]
Hi @intstringnum, thanks for your interest! x is a vector because there can be more than one public IO in a circuit.
