### ISSUE TITLE
Move to actual `group` traits and create `GroupExt` for the extra extensions of the `Group` trait

### ISSUE THREAD

**Issue by CPerezz** [microsoft/Nova#198]
One thing I've noticed and it's quite confusing from this repo is that it re-implements the `Group` trait.
I've been playing arround with this and I think it should be possible to use the original `group::Group` trait and create here a `GroupExt` trait that extends the missing features of `Group` to be able to do everything needed (have the attached commitment scheme traits for example..).

This would reduce duplication of code and also reduce the complexity of the lib significantly. Also, we can later check with the Zcash people to see which things would make sense to upstream to their `group` crate.

If that's something interesting, I'd love to work on it! So just let me know!

**Comment by srinathsetty** [comment]
Hi @CPerezz! Thanks for the suggestion! Yes, it would certainly be interesting to investigate this.

**Comment by ashWhiteHat** [comment]
I think that makes sense to me to add `Base` field type to upstream `group`

**Comment by srinathsetty** [comment]
I think this issue may not longer be necessary as much of the original `Group` crate has been refactored into the provider module.

**Comment by CPerezz** [comment]
> I think this issue may not longer be necessary as much of the original `Group` crate has been refactored into the provider module.

Makes sense!  In any case, my hope is that we can at some point refactor `ff` and `group` on a way on which we can just get ridd of the provider module directly.
