### ISSUE TITLE
Support accelerated MSM for halo2curves/grumpkin

### ISSUE THREAD

**Issue by huitseeker** [microsoft/Nova#216]
The [pasta cycle imports](https://github.com/microsoft/Nova/blob/ce470e7ffc4d57ca0b21de036cd18933561ec888/src/provider/pasta.rs#L70-L88) a GPU-accelerated MSM through the [`pasta-msm` crate](https://github.com/supranational/pasta-msm).
This crate is backed by the [Sppark library](https://github.com/supranational/sppark), which is generic in the curve parameters it operates with. 

With another shim (similar to pasta-msm, but adapted to the parameters of the grumpkin cycle), we could have GPU acceleration of the MSM on the Grumpkin / BN254 cycle.

**Comment by srinathsetty** [comment]
Hi @huitseeker, is it feasible to make pasta-msm support a collection of curves (including BN254/Grumpkin)? It would be better than having two crates one for pasta curves and another for bn254/grumpkin.

**Comment by CPerezz** [comment]
We can explore trying integrating the GPU acceleration in halo2-curves if we can somehow make it use the generalizations of the `pasta-msm` crate. But not sure we have the bandwidth. So would be nice to know if it's even feasible (architecturally-wise) to end up with something that makes sense and is manteinable. 

Happy to upstream any speedups under an experimental feature for sure!

**Comment by srinathsetty** [comment]
@huitseeker should this issue be filed in halo2curves repo rather than here? It seems there is not much to be done in the Nova repository to address this issue.

**Comment by srinathsetty** [comment]
Fantastic! Looking forward to it!

**Comment by srinathsetty** [comment]
Since this is an action item for the underlying crypto library rather than Nova library, closing it here.
