### ISSUE TITLE
Modules are not public

### ISSUE THREAD

**Issue by arthurgreef** [microsoft/Nova#26]
Hi - the circuit, gadgets, and poseidon modules are not public. Can we make them public?

pub mod bellperson;
mod circuit;
pub mod errors;
mod gadgets;
pub mod pasta;
mod poseidon;
pub mod r1cs;
pub mod traits;

**Comment by srinathsetty** [comment]
@arthurgreef circuit.rs and poseidon.rs are meant to be used internally. Is there a reason you need it to be exposed? We could certainly make gadgets public.

**Comment by arthurgreef** [comment]
I need gadgets for sure. I can reevaluate when I get into hashing for signature verification. Thanks.

**Comment by srinathsetty** [comment]
fixed by #39
