### ISSUE TITLE
Re-export Field/Point types used in curve cycle implementations

### ISSUE THREAD

**Issue by huitseeker** [microsoft/Nova#271]
#267 made the provider modules, notably the two field types and the two point types for each curve cycle, private, only exposing the Engine.

However, downstream users of nova may eventually need to use a distinct version of the libraries Nova uses for those providers, and should they not be able to exactly match that version, they would no longer have a handle on those field and point types, which would make them incapable of implementing traits on them, etc.

See https://www.lurklurk.org/effective-rust/re-export.html for a comprehensive description of this issue.

A good practice would be to re-export either the entire dependency crates (`pasta_curves`, `halo2curves`) or the four core types used in the provider module. The bn256_grumpkin cycle, for instance, forms a handy set of aliases (aimed at making the halo2curves types amenable to the nova curves macros) that could be re-exported:
https://github.com/microsoft/Nova/blob/2209a4fc7e2240962a9c5a3318109eb6cc8b831d/src/provider/bn256_grumpkin.rs#L30-L32

**Comment by srinathsetty** [comment]
Hi @huitseeker,

I must be missing something. The public interface of Nova does not involve the Point type. Isn't it? The step circuit that upstream needs to pass to Nova is defined only over a prime field that must match an associate type (`Scalar`) in Engine trait. Isn't it?

**Comment by huitseeker** [comment]
The encapsulation of all group types (notably those used in public parameters, constraining their generation to either of:
- using the provided Nova methods,
- type-unsafe methods including byte-mimicry followed by deserialization) in Nova types is in my opinion suboptimal. But that can certainly be tabled to a distinct discussion, as I suspect issues like #270 will force us to tackle this issue.

We don't even need the point types to show the issue:
https://gist.github.com/huitseeker/cc0567e62b53828d0581c83241a6b6ac

**Comment by srinathsetty** [comment]
> It would be particularly useful to have access to the specific Scalar::from_bytes method that Nova expects, in order to feed it the type it requires.

I'm still confused about this comment. Where exactly does Nova expects from_bytes method?

**Comment by huitseeker** [comment]
@srinathsetty the turn of phrase is unfortunate, what I meant is 
> It would be particularly useful to have access[^1] to the specific `Scalar::from_bytes` method so that a dependent crate can feed Nova the specific types it requires.

[^1]: through a re-export.

What Nova expects is the type: Scalars (among others) of an opaque (from the point of view of a Nova dependent) version of the pasta/halo2curves crates. Absent a re-export, the dependent will happen to be able to replicate those types if and only if its versions of those Scalars coincide with those Nova uses.

On the other hand, if Nova re-exports its dependencies, then the dependent, as long as it has access to bytes, can always deserialize data to the particular types Nova expects, using bytes-to-type conversion methods such as `Scalar::from_btyes`.

**Comment by srinathsetty** [comment]
Thanks for the details! IIUC, this only requires exporting Scalar types, not the point types used internally by Nova, right?

**Comment by huitseeker** [comment]
> IIUC, this only requires exporting Scalar types, not the point types used internally by Nova, right?

This only requires re-exporting types from `halo2curves` (and `pasta_curves`) that appear in Nova's public APIs.

**Comment by srinathsetty** [comment]
Addressed in #343
