### ISSUE TITLE
Middleware to load Noir's ACIR into R1CS supported by Nova

### ISSUE THREAD

**Issue by srinathsetty** [microsoft/Nova#275]
Nova accepts circuits written with bellpepper. If one writes a middleware (analogous to Noir's arkworks backend) to parse and load ACIR (and witness) into a bellpepper circuit, one can then prove the execution of Noir programs with Nova.

**Comment by Sun-Jc** [comment]
One implementation is [here](https://github.com/Sun-Jc/noir-ivc/blob/main/src/tests.rs).

**Comment by srinathsetty** [comment]
Closing it here given https://github.com/Sun-Jc/noir-ivc/blob/main/src/tests.rs
