### ISSUE TITLE
Remove redundant absorbing to the transcript

### ISSUE THREAD

**Issue by storojs72** [microsoft/Nova#284]
One of `CompressedSNARK`'s verification steps (affects only [ppspartan.rs](https://github.com/microsoft/Nova/blob/main/src/spartan/ppsnark.rs)) - checking the satisfiability of the folded instances ([link](https://github.com/microsoft/Nova/blob/main/src/lib.rs#L833)) - has [following](https://github.com/microsoft/Nova/blob/main/src/spartan/ppsnark.rs#L1367) redundant absorption of `eval_vec` to the transcript, since it is already happened [here](https://github.com/microsoft/Nova/blob/main/src/spartan/ppsnark.rs#L1346). Absorbing the same value twice adds no new entropy to the transcript, so second one can be freely removed.

I'm happy to provide a hotfix for this in case if core contributors confirm the issue

**Comment by srinathsetty** [comment]
Hi @storojs72, thanks the report! Yes, they are indeed absorbed twice (this is not a correctness issue, but a cost that does not need to be paid). Yes, please submit a fix.
