### ISSUE TITLE
How does Nova constrain prev output and next input?

### ISSUE THREAD

**Issue by ClankPan** [microsoft/Nova#296]
Which part does it constrain previous output and next input?

**Comment by srinathsetty** [comment]
Hi @ClankPan, you can see this in action here: https://github.com/microsoft/Nova/blob/8244d00a7b3bf5fc44e8cf76c3a0d67cfdb17394/src/circuit.rs#L329

z_input is selected based on the output of the prior step or `z_0` here (depending on whether we are in base case or not): https://github.com/microsoft/Nova/blob/8244d00a7b3bf5fc44e8cf76c3a0d67cfdb17394/src/circuit.rs#L322
