### ISSUE TITLE
Compilation on 32-bit architectures

### ISSUE THREAD

**Issue by pgrinaway** [microsoft/Nova#318]
Hi all,

Thanks for the very cool project. Has anyone tried to compile `Nova` for a 32-bit architecture? I think it has a transitive dependency somewhere on an older version of `typenum` that uses const generic `usize` greater than `usize::MAX` on 32-bit machines. Just wondering if anyone has found a simple workaround.

Thanks!

Patrick

**Comment by srinathsetty** [comment]
Hi @pgrinaway thanks for your interest!

I'm not aware of someone trying it on 32-bit architecture. Is it possible to override the typenum dependency in the dependency tree by editing Cargo.toml?

**Comment by srinathsetty** [comment]
Closing this!
