### ISSUE TITLE
Solidity Verfier

### ISSUE THREAD

**Issue by Ayoub-47** [microsoft/Nova#319]
Hello, is there an existing solidity verifer for Nova?

**Comment by srinathsetty** [comment]
Hi @Ayoub-47 It does not exist, yet.

**Comment by tazullogicuk** [comment]
You can try this: https://github.com/lurk-lab/solidity-verifier however, there have few others verifier available.

**Comment by srinathsetty** [comment]
This is already tracked in #116, so closing this.
