### ISSUE TITLE
[question] Where to find the example for matrix multiplication recursive snark

### ISSUE THREAD

**Issue by 123123davejohn** [microsoft/Nova#322]
I find the "and" example in the github repo. However, I was looking for a matrix multiplication example (c = a x b, where a, b, and c are configurable size matrices). Do you have an example for matrix multiplication similar to that of the "and" example?  And if so, could you please share it with me.

**Comment by srinathsetty** [comment]
We don't have such an example. 

Depending on your familiarity with bellpepper, it should be relatively easy to write it up. In particular, take entries of a, b, and c as witness elements and then implement the naive matrix multiplication algorithm.

**Comment by srinathsetty** [comment]
Closing this! Please reopen if you have further questions.
