### ISSUE TITLE
Upgrade the constraint system module

### ISSUE THREAD

**Issue by srinathsetty** [microsoft/Nova#331]
The current Nova codebase relies on bellpepper and bellpepper-core libraries to synthesize R1CS matrices (see e.g., bellpepper module in this codebase). This has several limitations:

* The constraint systems are deterministic, so they do not allow randomized checks within a circuit. This limits circuits from leveraging certain functionality e.g., lookup protocols, read-write memory, etc.
* The constraint system only has `aux` and `input` types for variables in a constraint systems. For supporting randomized checks, we would minimally need one additional type of variable e.g., `precommitted`. These precommitted-values can be "carried" (e.g., as in the Nebula paper).
* The constraint system is limited to R1CS, so there is no support for more advanced constraint systems such as CCS.

To address this, a *starting point* would be to make the constraint system module in Nova code base "self sufficient" i.e., implement the underlying ConstraintSystem trait, basic gadgets, etc. directly inside Nova codebase (this would eliminate dependency on bellpepper-core and bellpepper).

A side effect is we need a Poseidon Sponge implementation compatible with the constraint system types hosted in Nova codebase.

**Comment by Forpee** [comment]
Started working on this.
